# Generated by Django 3.2.3 on 2021-08-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='registertime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
